# This file is part of web-eremote-mini.
# https://github.com/garaemon/web-eremote-mini

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2017, Ryohei Ueda <garaemon@gmail.com>

language: python

python:
    - "3.4"
    - "pypy"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
